let tracksArray = [
  "Alec Makinson - Jazzy Bell Jingle (Main).mp3",
  "Alexander Khaskin - Silent Night Dixieland.mp3",
  "Anthony Hugh - It Came Upon A Midnight Clear.mp3",
  "Anthony Hugh - Joy To The World.mp3",
  "Anthony Hugh - Joyful Joyful We Adore Thee.mp3",
  "Antoinette Tredanary - Happy Holiday.mp3",
  "Audioquattro - Blitzen.mp3",
  "Badabing Badaboom - Christmas Morning.mp3",
  "Bamford Stevens - It Came Upon The Midnight Clear.mp3",
  "Beepcode - Christmas Ball.mp3",
  "Beepcode - It's My Christmas Dream.mp3",
  "Bernard Leclerc - Celebrate Christmas Day.mp3",
  "Botabateau - Christmas Carol.mp3",
  "Brian Thomas Curtin - Joy To The World.mp3",
  "Brian Thomas Curtin - O Christmas Tree (O Tannenbaum).mp3",
  "Brian Thomas Curtin - We Wish You A Merry Christmas.mp3",
  "Danny Jones - Deck The Halls.mp3",
  "Danny Jones - Jingle Bells.mp3",
  "Fabrice Mogini - Jingle Bells Bossa.mp3",
  "Fyodor - Christmas Day.mp3",
  "Jive Ass Sleepers - God Rest Ye Funky Gentlemen.mp3",
  "Joe Pignato - Almost Time For Christmas.mp3",
  "John Altenburgh - We Wish You A Merry Christmas.mp3",
  "Joseph Rusnak - A Ukelele Christmas.mp3",
  "Kevin Saunders Hayes - Christmas On Main Street.mp3",
  "Klm Music - Christmas Is Coming.mp3",
  "Klm Music - Christmas Light.mp3",
  "Klm Music - My Magic Christmas.mp3",
  "Mark S. Crocker - Deck The Halls.mp3",
  "Martin Fackovec - Let The Christmas Spirit In.mp3",
  "Max Dicarlo - Christmas World.mp3",
  "Max Dicarlo - My Sweet Sweet Christmas.mp3",
  "Michael Warner - A Ring Ding Christmas Swing.mp3",
 " Mykyta Moiseiev - Christmas Is Coming, Pt.2.mp3",
  "Nicholas Difabbio - Beautiful Christmas Melody.mp3",
  "Noel Mcloughlin - I Saw Three Ships.mp3",
  "Peter Roe - Dancing Corals.mp3",
  "Regina Smoler - Jingle Bells.mp3",
  "Richard Freitas - Midnight Clear.mp3",
  "Richard J Freitas - Gumdrops.mp3",
  "Ron Komie - God Rest Ye Merry Gentlemen, Vol. 3.mp3",
  "Ron Komie - Good Christians All Rejoice.mp3",
  "Ron Komie - Here We Come A'caroling Vol 5.mp3",
  "Ron Komie - I Saw Three Ships, Vol. 3.mp3",
  "Ron Komie - The First Noel.mp3",
  "Snowmen - Here Comes The Snowman.mp3",
  "Soundroad - Christmas Fair.mp3",
  "Steve Dafoe - Im Flying Home For Christmas.mp3",
  "Steve Dafoe - Racing Reindeer In The Snow.mp3",
  "The Ethnotronic Project - Magic Journey For Christmas.mp3",
  "The Hollytones - Christmas Bonus.mp3",
  "Tim Brown - Holiday Shopping.mp3",
  "Tim Brown - Jingle Bells At The Mall.mp3",
  "Tim Brown - Longing For Christmas.mp3",
  "Various Artists - Beautiful Christmas Day (Artist- Antoinette Tredanary).mp3"];

  const tracks = tracksArray.map((item) => {
    const obj ={};
    obj.src = "E:\\MUSIC\\" + item;
    obj.name = item;
    return obj;
  });

  export default tracks;
